# -*- coding: utf-8 -*-
"""Performance Testing & Hyperparameter Tuning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vvLSdPGZctnDaC5rM7JOZmdB78vvtoeW

# Save The Best Model
"""

import pandas as pd
from tensorflow.keras.models import Model
import pickle

df=pd.read_csv('loan.2023.csv')
df.head()

pickle . dump(Model,open('rdf.pkl','wb'))

"""# Integrate With Web Framework"""

